/* Generated By:JavaCC: Do not edit this line. OpeningHoursParserConstants.java */
package ch.poole.openinghoursparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OpeningHoursParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int SEMICOLON = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int HYPHEN = 9;
  /** RegularExpression Id. */
  int SLASH = 10;
  /** RegularExpression Id. */
  int QUOTE = 11;
  /** RegularExpression Id. */
  int ENDQUOTE = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int MINUTES = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int WS = 17;
  /** RegularExpression Id. */
  int FALLBACKSEPERATOR = 18;
  /** RegularExpression Id. */
  int ALWAYS = 19;
  /** RegularExpression Id. */
  int WEEKDAY = 20;
  /** RegularExpression Id. */
  int WEEKDAY3 = 21;
  /** RegularExpression Id. */
  int MONTH = 22;
  /** RegularExpression Id. */
  int HOLIDAYS = 23;
  /** RegularExpression Id. */
  int EVENTS = 24;
  /** RegularExpression Id. */
  int VARDATE = 25;
  /** RegularExpression Id. */
  int MODIFIER = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\" \"",
    "\"\\t\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"\\\"\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<NUMBER>",
    "<MINUTES>",
    "<DIGIT>",
    "<WS>",
    "\"||\"",
    "\"24/7\"",
    "<WEEKDAY>",
    "<WEEKDAY3>",
    "<MONTH>",
    "<HOLIDAYS>",
    "<EVENTS>",
    "\"easter\"",
    "<MODIFIER>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"day\"",
    "\"s\"",
    "\"week\"",
  };

}
