/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 3;
  /** RegularExpression Id. */
  int SEMICOLON = 4;
  /** RegularExpression Id. */
  int COLON = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int HYPHEN = 7;
  /** RegularExpression Id. */
  int SLASH = 8;
  /** RegularExpression Id. */
  int DOUBLEQUOTE = 9;
  /** RegularExpression Id. */
  int ENDQUOTE = 10;
  /** RegularExpression Id. */
  int EVERYTHINGEXCEPTDOUBLEQOUTES = 11;
  /** RegularExpression Id. */
  int HOUR = 12;
  /** RegularExpression Id. */
  int EXTENDEDHOUR = 13;
  /** RegularExpression Id. */
  int MINUTES = 14;
  /** RegularExpression Id. */
  int ONE2FIVE = 15;
  /** RegularExpression Id. */
  int YEAR = 16;
  /** RegularExpression Id. */
  int DAYNUM = 17;
  /** RegularExpression Id. */
  int WEEKNUM = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int WS = 21;
  /** RegularExpression Id. */
  int FALLBACKSEPERATOR = 22;
  /** RegularExpression Id. */
  int ALWAYS = 23;
  /** RegularExpression Id. */
  int WEEKDAY = 24;
  /** RegularExpression Id. */
  int MONTH = 25;
  /** RegularExpression Id. */
  int HOLIDAYS = 26;
  /** RegularExpression Id. */
  int EVENTS = 27;
  /** RegularExpression Id. */
  int VARDATE = 28;
  /** RegularExpression Id. */
  int MODIFIER = 29;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"\\\"\"",
    "<ENDQUOTE>",
    "<EVERYTHINGEXCEPTDOUBLEQOUTES>",
    "<HOUR>",
    "<EXTENDEDHOUR>",
    "<MINUTES>",
    "<ONE2FIVE>",
    "<YEAR>",
    "<DAYNUM>",
    "<WEEKNUM>",
    "<NUMBER>",
    "<DIGIT>",
    "<WS>",
    "\"||\"",
    "\"24/7\"",
    "<WEEKDAY>",
    "<MONTH>",
    "<HOLIDAYS>",
    "<EVENTS>",
    "\"easter\"",
    "<MODIFIER>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"day\"",
    "\"s\"",
    "\"week\"",
  };

}
